modLoader = "javafml"
loaderVersion = "[47,)"
license = "generated at build time"

[[mods]]
modId = "generated-at-build-time"
version = "generated at build time"
displayName = "generated at build time"

[[dependencies.generated-at-build-time]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.generated-at-build-time]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"