# suppress inspection "SpellCheckingInspection" for whole file
# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.caching=false
org.gradle.configuration-cache=false
# Mod properties
mod.id=i_have_slept
mod.name=I have slept
mod.group=dev.aika.i_have_slept
mod.version=1.1.2
mod.enabled_platforms=fabric,neoforge
mod.license=MIT
