modLoader = "javafml"
loaderVersion = "[4,)"
license = "generated at build time"

[[mods]]
modId = "generated-at-build-time"
version = "generated at build time"
displayName = "generated at build time"

[[dependencies.generated-at-build-time]]
modId = "neoforge"
type = "required"
versionRange = "[26,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.generated-at-build-time]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "i_have_slept.mixins.json"

[modproperties.modmenu]
links = ["modmenu.donate=https://afdian.com/a/gizmo"]